name: Merge CSV Files

on:
  schedule:
    - cron: '*/10 * * * *'  # Runs every 10 minutes
    
  workflow_dispatch:  # Allows manual triggering

jobs:
  merge_csv:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Pandas
        run: pip install pandas

      - name: Run CSV Merge Script
        run: python IWWRMP/Data/Suggestion/merge_csv.py

      - name: Check if there are changes to commit
        run: |
          if ! git diff --exit-code; then
            git add IWWRMP/Data/Suggestion/suggestion.csv
            git commit -m "Merged CSV files"
            git push
          else
            echo "No changes detected, skipping commit."
          fi
