name: Merge CSV Files

on:
  schedule:
    - cron: '*/10 * * * *'  # Runs every 10 minutes
  workflow_dispatch:  # Allows manual triggering

jobs:
  merge_csv:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Pandas
        run: pip install pandas

      - name: Run CSV Merge Script
        run: python IWWRMP/Data/Suggestion/merge_csv.py

      - name: Configure Git user
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Check if there are changes to commit
        run: |
          # Stage the file deletions and changes
          git add IWWRMP/Data/Suggestion/suggestion.csv
          git rm IWWRMP/Data/Suggestion/suggestion_*.csv || echo "No files to remove"
          
          # Check if there are any changes to commit
          git diff --exit-code || (
            git commit -m "Merged CSV files and removed old suggestion files"
          )

      - name: Push changes to repository
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}  # GitHub token for authentication
        run: |
          git push
